<?php

namespace App\Providers;

use App\Services\Impl\TodolistServicesDbImpl;
use App\Services\Impl\TodolistServicesImpl;
use App\Services\TodolistServices;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class TodolistServiceProvider extends ServiceProvider implements DeferrableProvider
{
    public array $singletons = [
        TodolistServices::class => TodolistServicesDbImpl::class
    ];

    public function provides() :array
    {
        return [TodolistServices::class];// TODO: Change the autogenerated stub
    }

    /**
     * Register services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}
